### ISSUE TITLE
Welcoming Problem Solvers For Hacktober Fest 🔥🔥

### ISSUE THREAD

**Issue by siddeshshewde** [siddeshshewde/Algorithms#2]
You can add any Algorithm in any language which you like. 
If you are adding in a new language, the folder structure would be:
Algorithms > [Language] > Math/Sorting/Searching/Data Structure > bubble_sort.py/.java/.c

Just an Example above.

Also, Make sure you are opening a new issue for adding an Algo so that there are no multiple users working on the same task.

**Comment by naveensd101** [comment]
Hi, I am interested in working on this repository.

**Comment by siddeshshewde** [comment]
@naveensd101 : Sure buddy, you can open a new issue with the label as algorithm name like if you want to add say selection sort in java, then open as an issue labeled as Selection Sort in Java.

Will assign it to you :)

**Comment by naveensd101** [comment]
I opened an issue.

**Comment by siddeshshewde** [comment]
> I opened an issue.

@naveensd101 
Assigned [Quick Sort in C] to you
